
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - clusterops.simeonpoot.nl
  resources:
  - troubleshooters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clusterops.simeonpoot.nl
  resources:
  - troubleshooters/finalizers
  verbs:
  - update
- apiGroups:
  - clusterops.simeonpoot.nl
  resources:
  - troubleshooters/status
  verbs:
  - get
  - patch
  - update
