# permissions for end users to edit troubleshooters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: troubleshooter-editor-role
rules:
- apiGroups:
  - clusterops.simeonpoot.nl
  resources:
  - troubleshooters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clusterops.simeonpoot.nl
  resources:
  - troubleshooters/status
  verbs:
  - get
