apiVersion: clusterops.simeonpoot.nl/v1
kind: Troubleshooter
metadata:
  name: troubleshooter-sample2
  namespace: test
spec:
  # Add fields here
  foo: bar
  image: "nginx"
  podName: "baz"
  Session:
    duration: 2 # in Minutes/ TODO: we need to configure a default
  createNamespace: true
